/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Colibri({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('../../models/210604_Colibri');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.ArmatureAction.play();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="05_Colibri_Bird001">
          <primitive object={nodes.Body001} />
          <skinnedMesh
            name="05_Colibri001"
            geometry={nodes['05_Colibri001'].geometry}
            material={materials['05_Colibri_Bird_Body']}
            skeleton={nodes['05_Colibri001'].skeleton}
          />
        </group>
        <group name="05_Colibri_Bird002">
          <group
            name="BigBranch_Root001"
            position={[-7.04, -7.7, -0.49]}
            rotation={[-0.94, -0.83, -1.41]}
          >
            <group name="BigBranch_01001" position={[0, 3.48, 0]} rotation={[-0.37, -0.07, -0.24]}>
              <group name="BigBranch_02001" position={[0, 1.62, 0]} rotation={[0, -0.03, -0.04]}>
                <group
                  name="BigBranch_03001"
                  position={[0, 1.25, 0]}
                  rotation={[-0.28, -0.01, -0.07]}
                >
                  <group
                    name="BigBranch_04001"
                    position={[0, 1.79, 0]}
                    rotation={[-0.16, -0.02, 0.26]}
                  >
                    <group
                      name="BigBranch_05001"
                      position={[0, 2.3, 0]}
                      rotation={[-0.32, 0.03, -0.08]}
                    >
                      <group
                        name="BigBranch_06001"
                        position={[0, 1.5, 0]}
                        rotation={[0.98, 0.2, 0.1]}
                      >
                        <group
                          name="BigBranch_07001"
                          position={[0, 1.43, 0]}
                          rotation={[-0.31, -0.01, -0.03]}
                        >
                          <group
                            name="BigBranch_08001"
                            position={[0, 1.14, 0]}
                            rotation={[0.65, 0.2, 0.37]}
                          >
                            <group
                              name="BigBranch_09001"
                              position={[0, 1.23, 0]}
                              rotation={[0.42, 0.08, 0.06]}
                            >
                              <group
                                name="BigBranch_10001"
                                position={[0, 1.15, 0]}
                                rotation={[0.68, 0.23, 0.29]}
                              >
                                <group
                                  name="BigBranch_Flower_01001"
                                  position={[0, 0.79, 0]}
                                  rotation={[0.13, 0.03, 0.32]}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                      <group
                        name="BigBranch_Leaf_11001"
                        position={[0, 1.5, 0]}
                        rotation={[1.39, -0.35, 0.09]}
                      />
                      <group
                        name="BigBranch_Leaf_12001"
                        position={[0, 1.5, 0]}
                        rotation={[2.17, 0.86, 0.76]}
                      />
                      <group
                        name="BigBranch_Leaf_13001"
                        position={[0, 1.5, 0]}
                        rotation={[0.59, -0.03, -0.06]}
                      >
                        <group
                          name="BigBranchLeaf_13_01001"
                          position={[0, 1.43, 0]}
                          rotation={[-0.37, -0.08, 0.04]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="BigBranch_Leaf_08001"
                    position={[0, 1.79, 0]}
                    rotation={[1.24, 0.82, 0.13]}
                  />
                  <group
                    name="BigBranch_Leaf_09001"
                    position={[0, 1.79, 0]}
                    rotation={[-1.53, -0.18, 0.07]}
                  />
                </group>
                <group
                  name="BigBranch_Leaf_06001"
                  position={[0, 1.25, 0]}
                  rotation={[1.01, 0.26, 0.47]}
                />
                <group
                  name="BigBranch_Leaf_07001"
                  position={[0, 1.25, 0]}
                  rotation={[-1.12, 0.14, -0.35]}
                />
              </group>
              <group
                name="BigBranch_02_01001"
                position={[0, 1.62, 0]}
                rotation={[-0.96, -0.07, -0.22]}
              >
                <group
                  name="BigBranch_02_02001"
                  position={[0, 1.25, 0]}
                  rotation={[0.53, 0.09, 0.02]}
                >
                  <group
                    name="BigBranch_02_03_01001"
                    position={[0, 0.61, 0]}
                    rotation={[-0.8, 0.4, -0.19]}
                  >
                    <group
                      name="BigBranch_02_03_02001"
                      position={[0, 0.95, 0]}
                      rotation={[0.06, -0.01, 0.07]}
                    >
                      <group
                        name="BigBranch_02_03_Flower_03001"
                        position={[0, 1.13, 0]}
                        rotation={[0.15, -0.01, -0.37]}
                      >
                        <group
                          name="BigBranch_02_03_Flower_03_Petal_01001"
                          position={[0, 0.76, 0]}
                          rotation={[0.88, 0.33, 1.37]}
                        />
                        <group
                          name="BigBranch_02_03_Flower_03_Petal_02001"
                          position={[0, 0.76, 0]}
                          rotation={[-0.14, 0.08, -0.44]}
                        />
                        <group
                          name="BigBranch_02_03_Flower_03_Petal_03001"
                          position={[0, 0.76, 0]}
                          rotation={[-1.53, -0.33, 0.72]}
                        />
                        <group
                          name="BigBranch_02_03_Flower_03_Petal_04001"
                          position={[0, 0.76, 0]}
                          rotation={[0.06, 0.15, 0.87]}
                        />
                        <group
                          name="BigBranch_02_03_Flower_03_Petal_05001"
                          position={[0, 0.76, 0]}
                          rotation={[0.04, 0.12, 0.31]}
                        />
                        <group
                          name="BigBranch_02_03_Flower_03_Petal_06001"
                          position={[0, 0.76, 0]}
                          rotation={[-0.59, 0, 0]}
                        />
                        <group
                          name="BigBranch_02_03_Flower_03_Petal_07001"
                          position={[0, 0.76, 0]}
                          rotation={[-0.85, -0.35, 0.44]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="BigBranch_02_04_01001"
                    position={[0, 0.61, 0]}
                    rotation={[0.38, 0.08, 0.1]}
                  >
                    <group
                      name="BigBranch_02_04_02001"
                      position={[0, 1.06, 0]}
                      rotation={[-0.44, -0.02, -0.13]}
                    >
                      <group
                        name="BigBranch_02_04_Flower_04001"
                        position={[0, 1.13, 0]}
                        rotation={[-0.48, 0.01, -0.25]}
                      >
                        <group
                          name="BigBranch_02_04_Flower_04_Petal_01001"
                          position={[0, 1.07, 0]}
                          rotation={[0, 0.09, -0.08]}
                          scale={[0.2, 0, 0]}
                        />
                        <group
                          name="BigBranch_02_04_Flower_04_Petal_02001"
                          position={[0, 1.07, 0]}
                          rotation={[-0.94, -0.01, -0.21]}
                        />
                        <group
                          name="BigBranch_02_04_Flower_04_Petal_03001"
                          position={[0, 1.07, 0]}
                          rotation={[0.49, 0.44, 1.42]}
                        />
                        <group
                          name="BigBranch_02_04_Flower_04_Petal_04001"
                          position={[0, 1.07, 0]}
                          rotation={[-0.61, -0.19, 0.68]}
                        />
                        <group
                          name="BigBranch_02_04_Flower_04_Petal_05001"
                          position={[0, 1.07, 0]}
                          rotation={[0.72, -0.06, -0.11]}
                        />
                        <group
                          name="BigBranch_02_04_Flower_04_Petal_06001"
                          position={[0, 1.07, 0]}
                          rotation={[0.07, 0.46, 0.7]}
                        />
                        <group
                          name="BigBranch_02_04_Flower_04_Petal_07001"
                          position={[0, 1.07, 0]}
                          rotation={[-0.12, -0.03, -0.37]}
                        />
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="BigBranch_02_02_Flower_02001"
                  position={[0, 1.25, 0]}
                  rotation={[-1.24, 0.11, 0.2]}
                />
              </group>
            </group>
            <group
              name="BigBranch_Leaf_05001"
              position={[0, 3.48, 0]}
              rotation={[-0.06, 0.77, 1.59]}
            />
            <group
              name="BigBranch_Leaf_01001"
              position={[0, 3.48, 0]}
              rotation={[2.51, -0.72, -0.25]}
            />
            <group
              name="BigBranch_Leaf_02001"
              position={[0, 3.48, 0]}
              rotation={[-2.19, -0.26, -0.08]}
            />
            <group
              name="BigBranch_Leaf_03001"
              position={[0, 3.48, 0]}
              rotation={[0.14, 0.01, -0.4]}
            />
            <group
              name="BigBranch_Leaf_04001"
              position={[0, 3.48, 0]}
              rotation={[1.3, 0.04, 0.06]}
            />
          </group>
          <group
            name="SmallBranch_Petal_01_Fix"
            position={[-4.3, 5.22, 0.4]}
            rotation={[-0.31, -0.78, -2.91]}
          />
          <group
            name="SmallBranch_Petal_02_01_Fix"
            position={[-4.3, 5.22, 0.4]}
            rotation={[-2.99, 0.23, -0.22]}
          >
            <group
              name="SmallBranch_Petal_02_02"
              position={[0, 2.24, 0]}
              rotation={[-0.44, 0.01, -0.13]}
            />
          </group>
          <group
            name="SmallBranch_Petal_03_01_FIx"
            position={[-4.3, 5.22, 0.4]}
            rotation={[-2.66, -0.56, 0.41]}
          >
            <group
              name="SmallBranch_Petal_03_02"
              position={[0, 2.62, 0]}
              rotation={[-0.68, -0.13, -0.04]}
            />
          </group>
          <group
            name="SmallBranch_Petal_04_Fix"
            position={[-4.3, 5.22, 0.4]}
            rotation={[-1.85, -0.3, 0.88]}
          />
          <group
            name="SmallBranch_Petal_05_Fix"
            position={[-4.3, 5.22, 0.4]}
            rotation={[-1.6, 0.04, 1.12]}
          />
          <group
            name="SmallBranch_Petal_06_Fix"
            position={[-4.3, 5.22, 0.4]}
            rotation={[3.05, 0.4, 3.07]}
          />
          <group
            name="SmallBranch_Petal_07_01_Fix"
            position={[-4.3, 5.22, 0.4]}
            rotation={[-1.78, 0.69, -1.42]}
          >
            <group
              name="SmallBranch_Petal_07_02"
              position={[0, 2.31, 0]}
              rotation={[-0.11, 0.04, -0.52]}
            />
          </group>
          <group
            name="SmallBranch_01"
            position={[-4.3, 5.22, 0.4]}
            rotation={[-1.58, -0.32, -1.58]}
          >
            <group
              name="SmallBranch_Petal_08"
              position={[0, 1.03, 0]}
              rotation={[0.7, -0.04, -0.12]}
            />
            <group name="SmallBranch_02" position={[0, 1.03, 0]} rotation={[0.11, 0, 0.31]}>
              <group name="SmallBranch_02_01" position={[0, 1.3, 0]} rotation={[0.02, 0, -0.23]}>
                <group
                  name="SmallBranch_02_02"
                  position={[0, 1.97, 0]}
                  rotation={[-0.98, 0.35, -0.39]}
                >
                  <group
                    name="SmallBranch_02_Flower_01"
                    position={[0, 2.25, 0]}
                    rotation={[-0.03, 0.3, -0.28]}
                  />
                </group>
              </group>
            </group>
            <group name="SmallBranch_03" position={[0, 1.03, 0]} rotation={[-0.03, -0.21, 0.26]}>
              <group
                name="SmallBranch_03_01"
                position={[0, 2.28, 0]}
                rotation={[-0.52, 0.01, 0.14]}
              >
                <group
                  name="SmallBranch_03_Flower_02"
                  position={[0, 2.04, 0]}
                  rotation={[-0.73, -0.2, -0.12]}
                />
              </group>
            </group>
          </group>
        </group>
        <group name="05_Colibri_Bird003">
          <group
            name="BigBranch_Root001_1"
            position={[-7.04, -7.7, -0.49]}
            rotation={[-0.94, -0.83, -1.41]}
          >
            <group
              name="BigBranch_01001_1"
              position={[0, 3.48, 0]}
              rotation={[-0.37, -0.07, -0.24]}
            >
              <group name="BigBranch_02001_1" position={[0, 1.62, 0]} rotation={[0, -0.03, -0.04]}>
                <group
                  name="BigBranch_03001_1"
                  position={[0, 1.25, 0]}
                  rotation={[-0.28, -0.01, -0.07]}
                >
                  <group
                    name="BigBranch_04001_1"
                    position={[0, 1.79, 0]}
                    rotation={[-0.16, -0.02, 0.26]}
                  >
                    <group
                      name="BigBranch_05001_1"
                      position={[0, 2.3, 0]}
                      rotation={[-0.32, 0.03, -0.08]}
                    >
                      <group
                        name="BigBranch_06001_1"
                        position={[0, 1.5, 0]}
                        rotation={[0.98, 0.2, 0.1]}
                      >
                        <group
                          name="BigBranch_07001_1"
                          position={[0, 1.43, 0]}
                          rotation={[-0.31, -0.01, -0.03]}
                        >
                          <group
                            name="BigBranch_08001_1"
                            position={[0, 1.14, 0]}
                            rotation={[0.65, 0.2, 0.37]}
                          >
                            <group
                              name="BigBranch_09001_1"
                              position={[0, 1.23, 0]}
                              rotation={[0.42, 0.08, 0.06]}
                            >
                              <group
                                name="BigBranch_10001_1"
                                position={[0, 1.15, 0]}
                                rotation={[0.68, 0.23, 0.29]}
                              >
                                <group
                                  name="BigBranch_Flower_01001_1"
                                  position={[0, 0.79, 0]}
                                  rotation={[0.13, 0.03, 0.32]}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                      <group
                        name="BigBranch_Leaf_11001_1"
                        position={[0, 1.5, 0]}
                        rotation={[1.39, -0.35, 0.09]}
                      />
                      <group
                        name="BigBranch_Leaf_12001_1"
                        position={[0, 1.5, 0]}
                        rotation={[2.17, 0.86, 0.76]}
                      />
                      <group
                        name="BigBranch_Leaf_13001_1"
                        position={[0, 1.5, 0]}
                        rotation={[0.59, -0.03, -0.06]}
                      >
                        <group
                          name="BigBranchLeaf_13_01001_1"
                          position={[0, 1.43, 0]}
                          rotation={[-0.37, -0.08, 0.04]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="BigBranch_Leaf_08001_1"
                    position={[0, 1.79, 0]}
                    rotation={[1.24, 0.82, 0.13]}
                  />
                  <group
                    name="BigBranch_Leaf_09001_1"
                    position={[0, 1.79, 0]}
                    rotation={[-1.53, -0.18, 0.07]}
                  />
                </group>
                <group
                  name="BigBranch_Leaf_06001_1"
                  position={[0, 1.25, 0]}
                  rotation={[1.01, 0.26, 0.47]}
                />
                <group
                  name="BigBranch_Leaf_07001_1"
                  position={[0, 1.25, 0]}
                  rotation={[-1.12, 0.14, -0.35]}
                />
              </group>
              <group
                name="BigBranch_02_01001_1"
                position={[0, 1.62, 0]}
                rotation={[-0.96, -0.07, -0.22]}
              >
                <group
                  name="BigBranch_02_02001_1"
                  position={[0, 1.25, 0]}
                  rotation={[0.53, 0.09, 0.02]}
                >
                  <group
                    name="BigBranch_02_03_01001_1"
                    position={[0, 0.61, 0]}
                    rotation={[-0.8, 0.4, -0.19]}
                  >
                    <group
                      name="BigBranch_02_03_02001_1"
                      position={[0, 0.95, 0]}
                      rotation={[0.06, -0.01, 0.07]}
                    >
                      <group
                        name="BigBranch_02_03_Flower_03001_1"
                        position={[0, 1.13, 0]}
                        rotation={[0.15, -0.01, -0.37]}
                      >
                        <group
                          name="BigBranch_02_03_Flower_03_Petal_01001_1"
                          position={[0, 0.76, 0]}
                          rotation={[0.88, 0.33, 1.37]}
                        />
                        <group
                          name="BigBranch_02_03_Flower_03_Petal_02001_1"
                          position={[0, 0.76, 0]}
                          rotation={[-0.14, 0.08, -0.44]}
                        />
                        <group
                          name="BigBranch_02_03_Flower_03_Petal_03001_1"
                          position={[0, 0.76, 0]}
                          rotation={[-1.53, -0.33, 0.72]}
                        />
                        <group
                          name="BigBranch_02_03_Flower_03_Petal_04001_1"
                          position={[0, 0.76, 0]}
                          rotation={[0.06, 0.15, 0.87]}
                        />
                        <group
                          name="BigBranch_02_03_Flower_03_Petal_05001_1"
                          position={[0, 0.76, 0]}
                          rotation={[0.04, 0.12, 0.31]}
                        />
                        <group
                          name="BigBranch_02_03_Flower_03_Petal_06001_1"
                          position={[0, 0.76, 0]}
                          rotation={[-0.59, 0, 0]}
                        />
                        <group
                          name="BigBranch_02_03_Flower_03_Petal_07001_1"
                          position={[0, 0.76, 0]}
                          rotation={[-0.85, -0.35, 0.44]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="BigBranch_02_04_01001_1"
                    position={[0, 0.61, 0]}
                    rotation={[0.38, 0.08, 0.1]}
                  >
                    <group
                      name="BigBranch_02_04_02001_1"
                      position={[0, 1.06, 0]}
                      rotation={[-0.44, -0.02, -0.13]}
                    >
                      <group
                        name="BigBranch_02_04_Flower_04001_1"
                        position={[0, 1.13, 0]}
                        rotation={[-0.48, 0.01, -0.25]}
                      >
                        <group
                          name="BigBranch_02_04_Flower_04_Petal_01001_1"
                          position={[0, 1.07, 0]}
                          rotation={[0, 0.09, -0.08]}
                          scale={[0.2, 0, 0]}
                        />
                        <group
                          name="BigBranch_02_04_Flower_04_Petal_02001_1"
                          position={[0, 1.07, 0]}
                          rotation={[-0.94, -0.01, -0.21]}
                        />
                        <group
                          name="BigBranch_02_04_Flower_04_Petal_03001_1"
                          position={[0, 1.07, 0]}
                          rotation={[0.49, 0.44, 1.42]}
                        />
                        <group
                          name="BigBranch_02_04_Flower_04_Petal_04001_1"
                          position={[0, 1.07, 0]}
                          rotation={[-0.61, -0.19, 0.68]}
                        />
                        <group
                          name="BigBranch_02_04_Flower_04_Petal_05001_1"
                          position={[0, 1.07, 0]}
                          rotation={[0.72, -0.06, -0.11]}
                        />
                        <group
                          name="BigBranch_02_04_Flower_04_Petal_06001_1"
                          position={[0, 1.07, 0]}
                          rotation={[0.07, 0.46, 0.7]}
                        />
                        <group
                          name="BigBranch_02_04_Flower_04_Petal_07001_1"
                          position={[0, 1.07, 0]}
                          rotation={[-0.12, -0.03, -0.37]}
                        />
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="BigBranch_02_02_Flower_02001_1"
                  position={[0, 1.25, 0]}
                  rotation={[-1.24, 0.11, 0.2]}
                />
              </group>
            </group>
            <group
              name="BigBranch_Leaf_05001_1"
              position={[0, 3.48, 0]}
              rotation={[-0.06, 0.77, 1.59]}
            />
            <group
              name="BigBranch_Leaf_01001_1"
              position={[0, 3.48, 0]}
              rotation={[2.51, -0.72, -0.25]}
            />
            <group
              name="BigBranch_Leaf_02001_1"
              position={[0, 3.48, 0]}
              rotation={[-2.19, -0.26, -0.08]}
            />
            <group
              name="BigBranch_Leaf_03001_1"
              position={[0, 3.48, 0]}
              rotation={[0.14, 0.01, -0.4]}
            />
            <group
              name="BigBranch_Leaf_04001_1"
              position={[0, 3.48, 0]}
              rotation={[1.3, 0.04, 0.06]}
            />
          </group>
          <group
            name="SmallBranch_Petal_01_Fix_1"
            position={[-4.3, 5.22, 0.4]}
            rotation={[-0.31, -0.78, -2.91]}
          />
          <group
            name="SmallBranch_Petal_02_01_Fix_1"
            position={[-4.3, 5.22, 0.4]}
            rotation={[-2.99, 0.23, -0.22]}
          >
            <group
              name="SmallBranch_Petal_02_02_1"
              position={[0, 2.24, 0]}
              rotation={[-0.44, 0.01, -0.13]}
            />
          </group>
          <group
            name="SmallBranch_Petal_03_01_FIx_1"
            position={[-4.3, 5.22, 0.4]}
            rotation={[-2.66, -0.56, 0.41]}
          >
            <group
              name="SmallBranch_Petal_03_02_1"
              position={[0, 2.62, 0]}
              rotation={[-0.68, -0.13, -0.04]}
            />
          </group>
          <group
            name="SmallBranch_Petal_04_Fix_1"
            position={[-4.3, 5.22, 0.4]}
            rotation={[-1.85, -0.3, 0.88]}
          />
          <group
            name="SmallBranch_Petal_05_Fix_1"
            position={[-4.3, 5.22, 0.4]}
            rotation={[-1.6, 0.04, 1.12]}
          />
          <group
            name="SmallBranch_Petal_06_Fix_1"
            position={[-4.3, 5.22, 0.4]}
            rotation={[3.05, 0.4, 3.07]}
          />
          <group
            name="SmallBranch_Petal_07_01_Fix_1"
            position={[-4.3, 5.22, 0.4]}
            rotation={[-1.78, 0.69, -1.42]}
          >
            <group
              name="SmallBranch_Petal_07_02_1"
              position={[0, 2.31, 0]}
              rotation={[-0.11, 0.04, -0.52]}
            />
          </group>
          <group
            name="SmallBranch_01_1"
            position={[-4.3, 5.22, 0.4]}
            rotation={[-1.58, -0.32, -1.58]}
          >
            <group
              name="SmallBranch_Petal_08_1"
              position={[0, 1.03, 0]}
              rotation={[0.7, -0.04, -0.12]}
            />
            <group name="SmallBranch_02_1" position={[0, 1.03, 0]} rotation={[0.11, 0, 0.31]}>
              <group name="SmallBranch_02_01_1" position={[0, 1.3, 0]} rotation={[0.02, 0, -0.23]}>
                <group
                  name="SmallBranch_02_02_1"
                  position={[0, 1.97, 0]}
                  rotation={[-0.98, 0.35, -0.39]}
                >
                  <group
                    name="SmallBranch_02_Flower_01_1"
                    position={[0, 2.25, 0]}
                    rotation={[-0.03, 0.3, -0.28]}
                  />
                </group>
              </group>
            </group>
            <group name="SmallBranch_03_1" position={[0, 1.03, 0]} rotation={[-0.03, -0.21, 0.26]}>
              <group
                name="SmallBranch_03_01_1"
                position={[0, 2.28, 0]}
                rotation={[-0.52, 0.01, 0.14]}
              >
                <group
                  name="SmallBranch_03_Flower_02_1"
                  position={[0, 2.04, 0]}
                  rotation={[-0.73, -0.2, -0.12]}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          name="05_Colibri_SmallBrach"
          position={[-5.76, 7.36, 0.4]}
          rotation={[1.34, 0.13, 0.15]}
          scale={1.2}
        >
          <group name="SmallBranch_Petal_07" rotation={[0, 0, -Math.PI]} scale={0}>
            <group name="SmallBranch_Petal_07_01" rotation={[0, 0, -Math.PI]} scale={0} />
          </group>
          <group name="SmallBranch_Petal_06" rotation={[0, 0, -Math.PI]} scale={0}>
            <group name="SmallBranch_Petal_06_01" rotation={[0, 0, -Math.PI]} scale={0}>
              <group name="SmallBranch_Petal_06_02" rotation={[0, 0, -Math.PI]} scale={0} />
            </group>
          </group>
          <group name="SmallBranch_Petal_05" rotation={[0, 0, -Math.PI]} scale={0}>
            <group name="SmallBranch_Petal_05_01" rotation={[0, 0, -Math.PI]} scale={0}>
              <group name="SmallBranch_Petal_05_02" rotation={[0, 0, -Math.PI]} scale={0} />
            </group>
          </group>
          <group name="SmallBranch_Petal_03" rotation={[0, 0, -Math.PI]} scale={0}>
            <group name="SmallBranch_Petal_03_01" rotation={[0, 0, -Math.PI]} scale={0} />
          </group>
          <group name="SmallBranch_Petal_04" rotation={[0, 0, -Math.PI]} scale={0}>
            <group name="SmallBranch_Petal_04_01" rotation={[0, 0, -Math.PI]} scale={0} />
          </group>
          <group name="SmallBranch_Petal_02" rotation={[0, 0, -Math.PI]} scale={0}>
            <group name="SmallBranch_Petal_02_01" rotation={[0, 0, -Math.PI]} scale={0} />
          </group>
          <group name="SmallBranch_Petal_01" rotation={[0, 0, -Math.PI]} scale={0}>
            <group name="SmallBranch_Petal_01_01" rotation={[0, 0, -Math.PI]} scale={0} />
          </group>
          <group name="SmallBranch_Leaf_to_Branch" rotation={[0, 0, -Math.PI]} scale={0}>
            <group name="SmallBranch_Branch_02" rotation={[0, 0, -Math.PI]} scale={0}>
              <group name="SmallBranch_Branch_02_01" rotation={[0, 0, -Math.PI]} scale={0}>
                <group
                  name="SmallBranch_Branch_02_Flower_02"
                  rotation={[0, 0, -Math.PI]}
                  scale={0}
                />
              </group>
            </group>
            <group name="SmallBranch_Branch_01" rotation={[0, 0, -Math.PI]} scale={0}>
              <group name="SmallBranch_Branch_01_01" rotation={[0, 0, -Math.PI]} scale={0}>
                <group name="SmallBranch_Branch_01_02" rotation={[0, 0, -Math.PI]} scale={0}>
                  <group
                    name="SmallBranch_Branch_01_Flower_01"
                    rotation={[0, 0, -Math.PI]}
                    scale={0}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group
          name="05_Colibri_BigBrach"
          position={[-7.7, -8.39, -1.3]}
          rotation={[1.85, 0.17, 0.13]}
        >
          <group name="BigBranch_01" rotation={[0, 0, -Math.PI]} scale={0}>
            <group name="BigBranch_02" rotation={[0, 0, -Math.PI]} scale={0}>
              <group name="BigBranch_03" rotation={[0, 0, -Math.PI]} scale={0}>
                <group name="BigBranch_04" rotation={[0, 0, -Math.PI]} scale={0}>
                  <group name="BigBranch_05" rotation={[0, 0, -Math.PI]} scale={0}>
                    <group name="BigBranch_06" rotation={[0, 0, -Math.PI]} scale={0}>
                      <group name="BigBranch_07" rotation={[0, 0, -Math.PI]} scale={0}>
                        <group name="BigBranch_08" rotation={[0, 0, -Math.PI]} scale={0}>
                          <group name="BigBranch_09" rotation={[0, 0, -Math.PI]} scale={0}>
                            <group name="BigBranch_10" rotation={[0, 0, -Math.PI]} scale={0}>
                              <group name="BigBranch_11" rotation={[0, 0, -Math.PI]} scale={0}>
                                <group name="BigBranch_12" rotation={[0, 0, -Math.PI]} scale={0}>
                                  <group
                                    name="BigBranch_Flower_04"
                                    rotation={[0, 0, -Math.PI]}
                                    scale={0}
                                  />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                        <group name="BigBranch_Leaf_07" rotation={[0, 0, -Math.PI]} scale={0} />
                        <group name="BigBranch_Leaf_08_01" rotation={[0, 0, -Math.PI]} scale={0}>
                          <group
                            name="BigBranch_Leaf_08_02"
                            rotation={[0, 0, -Math.PI]}
                            scale={0}
                          />
                        </group>
                        <group name="BigBranch_Leaf_06" rotation={[0, 0, -Math.PI]} scale={0} />
                      </group>
                    </group>
                  </group>
                  <group name="BigBranch_Leaf_05" rotation={[0, 0, -Math.PI]} scale={0} />
                  <group name="BigBranch_Leaf_04" rotation={[0, 0, -Math.PI]} scale={0} />
                </group>
                <group name="BigBranch_SmallBranch_02" rotation={[0, 0, -Math.PI]} scale={0}>
                  <group name="BigBranch_SmallBranch_03" rotation={[0, 0, -Math.PI]} scale={0}>
                    <group name="BigBranch_SmallBranch_04" rotation={[0, 0, -Math.PI]} scale={0}>
                      <group name="BigBranch_Flower_02" rotation={[0, 0, -Math.PI]} scale={0}>
                        <group
                          name="BigBranch_Flower_02_01"
                          rotation={[0, 0, -Math.PI]}
                          scale={0}
                        />
                        <group
                          name="BigBranch_Flower_02_03"
                          rotation={[0, 0, -Math.PI]}
                          scale={0}
                        />
                        <group
                          name="BigBranch_Flower_02_04"
                          rotation={[0, 0, -Math.PI]}
                          scale={0}
                        />
                        <group
                          name="BigBranch_Flower_02_02"
                          rotation={[0, 0, -Math.PI]}
                          scale={0}
                        />
                      </group>
                    </group>
                    <group name="BigBranch_SmallBranch_05" rotation={[0, 0, -Math.PI]} scale={0}>
                      <group name="BigBranch_SmallBranch_06" rotation={[0, 0, -Math.PI]} scale={0}>
                        <group name="BigBranch_Flower_03" rotation={[0, 0, -Math.PI]} scale={0}>
                          <group
                            name="BigBranch_Flower_03_01"
                            rotation={[0, 0, -Math.PI]}
                            scale={0}
                          />
                          <group
                            name="BigBranch_Flower_03_02"
                            rotation={[0, 0, -Math.PI]}
                            scale={0}
                          />
                          <group
                            name="BigBranch_Flower_03_03"
                            rotation={[0, 0, -Math.PI]}
                            scale={0}
                          />
                          <group
                            name="BigBranch_Flower_03_04"
                            rotation={[0, 0, -Math.PI]}
                            scale={0}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="BigBranch_Flower_01" rotation={[0, 0, -Math.PI]} scale={0}>
                    <group name="BigBranch_Flower_01_01" rotation={[0, 0, -Math.PI]} scale={0} />
                  </group>
                </group>
              </group>
              <group name="BigBranch_SmallBranch_01" rotation={[0, 0, -Math.PI]} scale={0} />
            </group>
            <group name="BigBranch_Leaf_01" rotation={[0, 0, -Math.PI]} scale={0} />
            <group name="BigBranch_Leaf_03" rotation={[0, 0, -Math.PI]} scale={0} />
            <group name="BigBranch_Leaf_02" rotation={[0, 0, -Math.PI]} scale={0} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('../../models/210604_Colibri');
